from .easy import TASK_DESCRIPTION as EASY_TASK_DESCRIPTION
from .hard import TASK_DESCRIPTION as HARD_TASK_DESCRIPTION
from .medium import TASK_DESCRIPTION as MEDIUM_TASK_DESCRIPTION

__all__ = [
	"EASY_TASK_DESCRIPTION",
	"MEDIUM_TASK_DESCRIPTION",
	"HARD_TASK_DESCRIPTION",
]
